project:
  type: website
  output-dir: docs

website:
  title: "Anirban Mandal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  
format:
  html:
    theme: theme.scss
    css: styles.css

callout-appearance: simple
callout-icon: false

comments: true
  giscus: true
    repo: AnirbanM13/AniNetwork1 
 
editor: visual

