project:
  type: website
  output-dir: docs

website:
  title: "Anirban Mandal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AnirbanM13
      - icon: twitter
        href: https://twitter.com/anirban___13
      - text: Blog
      - href: https://anirbanm13.github.io/AniNetwork1/
  
format:
  html:
    theme: theme.scss
    css: styles.css

callout-appearance: simple
callout-icon: false

comments: 
  giscus: 
    repo: "AnirbanM13/AniNetwork1" 
 
editor: visual

